### ISSUE TITLE
账号登不上去啊，不是登陆失败就是解锁，能不能解决下这个问题

### ISSUE THREAD

**Issue by guofucheng666** [cg3s/qa#11]
每次都是被锁定，真的心态炸了，有没有解决办法哦，过不了几天又是被锁定

**Comment by cg3s** [comment]
你确定是在App Store中登录的么

**Comment by guofucheng666** [comment]
对呀，就是appca@cgsss那个账户，我都发了邮件解锁

**Comment by cg3s** [comment]
你登录后为什么不退出？

**Comment by guofucheng666** [comment]
我都没登陆上去过，之前登上去下载了就退出了

**Comment by cg3s** [comment]
近段时间苹果封锁比较频繁，不封号还能解锁就算好了，
我们打算更新页面让用户自行购买app了，我们提供的账户只作为备选

**Comment by guofucheng666** [comment]
好吧，对了，专业套餐V1是没有了吗？

**Comment by cg3s** [comment]
那个就是现在的套装版

**Comment by guofucheng666** [comment]
好，谢谢

**Comment by cg3s** [comment]
不客气，另外现在账户-1是没有被锁的

**Comment by cg3s** [comment]
常用的设备要下app 一次就下完，不要今天下一个明天下一个，能免费下载到就算幸运

**Comment by guofucheng666** [comment]
好，我主要想更新app哈哈哈

**Comment by cg3s** [comment]
我们提供的三个账户已经算很厚道了，近期我们也非常烦恼，一天不在解锁中就在改密中
后面会更新网页提示，加上定期解锁的时间

**Comment by guofucheng666** [comment]
好的，辛苦了

**Comment by cg3s** [comment]
为用户(shang di men)服务:)
