### ISSUE TITLE
充值怎么充

### ISSUE THREAD

**Issue by ethanygt** [cg3s/qa#6]
原来是pro-专业版 A组，现在充值选哪个？
账户还有点余额怎么能在这次充值用上？

**Comment by cg3s** [comment]
你商店页面根据需求选就行，然后差多少钱就充多少嘛

**Comment by ethanygt** [comment]
原来是pro-专业版 A组对应的是哪个呢？

**Comment by ethanygt** [comment]
原来是pro-专业版 A组对应的是哪个呢？

**Comment by cg3s** [comment]
之前的专业版差不多等于现在的套装版，A组跟价格不相关

**Comment by ethanygt** [comment]
点击套餐上面有几点几折，是有折扣么

**Comment by cg3s** [comment]
那个就是跟按月订阅的价格所计算出的折扣
