### ISSUE TITLE
为什么不能访问  www.goliathguitartutorials.com

### ISSUE THREAD

**Issue by ethanygt** [cg3s/qa#7]
为什么不能访问  www.goliathguitartutorials.com

**Comment by cg3s** [comment]
<img width="933" alt="image" src="https://user-images.githubusercontent.com/28707826/76401879-8afc9800-63bd-11ea-9933-d41e2480c9aa.png">
试试洛杉矶节点

**Comment by ethanygt** [comment]
怎样才能在gfwlist里使用呢

**Comment by cg3s** [comment]
自己在节点设置页面添加pac规则，规则添加可参考已有的pac文件
